### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by haesleinhuepf** [NEUBIAS/bioimage-analysis-training-standards#2]
Hi all, hi Joanna @jpylvanainen ,

 would it be possible to add a license file to this repository? Published code/data without license is per European law copyright protected and cannot be reused. If there is a license file in this repository that allows us reusing the data that would be awesome.

See also:
* https://choosealicense.com/
* https://unlicense.org/

Thanks!

Best,
Robert

**Comment by tischi** [comment]
@haesleinhuepf we actually don't want to have any data in this repository; all data should go to the BIA where it would be CC-0.

**Comment by haesleinhuepf** [comment]
Ah, I see. Thanks for clarifying :-)
